import { Inter } from "next/font/google";
import "./globals.css";

import dynamic from "next/dynamic";
import { Toaster } from "react-hot-toast";
import Navbar from "../component/Navbar";

const ReduxProvider = dynamic(() => import("../redux/redux-provider"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
